version: '3.8'

services:
  messaging.publishservice.api:
    image: ${DOCKER_REGISTRY-}messagingpublisherapi
    build:
      context: .
      dockerfile: Modules/Publisher/Publisher.Api/Dockerfile
    container_name: messaging-publisher
    networks:
      - kafkanetwork
      - elasticsearchnetwork
    depends_on:
      - kafka
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        Elasticsearch__Url: http://elastic:9200
        EventBus__bootstrapservers: kafka:9092
        EventBus__groupid: messaging-publisher
        ElasticApm__ServerUrl: http://apm:8200

  messaging.consumerservice.api:
    image: ${DOCKER_REGISTRY-}messagingconsumerapi
    build:
      context: .
      dockerfile: Modules/Consumer/Consumer.Api/Dockerfile
    container_name: messaging-consumer
    networks:
      - kafkanetwork
      - elasticsearchnetwork
    depends_on:
      - kafka
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        Elasticsearch__Url: http://elastic:9200
        EventBus__bootstrapservers: kafka:9092
        EventBus__groupid: messaging-consumer
        EventBus__enableautocommit: "false"
        EventBus__statisticsintervalms: 5000
        EventBus__autooffsetreset: earliest
        EventBus__enablepartitioneof: "true"
        ElasticApm__ServerUrl: http://apm:8200

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
    - kafkanetwork
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: "wurstmeister/kafka"
    ports:
     - "9092:9092"
    hostname: kafka
    networks:
    - kafkanetwork
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - type: bind
          source: ./elasticsearchdata
          target: /usr/share/elasticsearch/data2
    networks:
        - elasticsearchnetwork
  kibana:
        image: docker.elastic.co/kibana/kibana:7.17.5
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - elasticsearchnetwork
        depends_on:
            - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:7.17.5
    container_name: apm
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    networks:
        - elasticsearchnetwork 
    depends_on:
        - elasticsearch
        - kibana
    command: >
      apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elastic:9200"]

volumes:
    elasticsearchdata:

networks:
  kafkanetwork:
    driver: bridge
  elasticsearchnetwork:
    driver: bridge