# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  logging:
    loglevel: debug
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "apm:8200"  
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic, prometheus]
    logs: 
      receivers: [otlp]
      processors: []
      exporters: [logging]