# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
        grpc:
        http:
exporters:
  logging:
    loglevel: info
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "apm:8200"  
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic, zipkin]
      processors: [batch]
    metrics:
        receivers: [otlp]
        exporters: [logging, otlp/elastic]
    logs: 
        receivers: [otlp]
        exporters: [logging, otlp/elastic]